---
- hosts: all
  become: yes

  tasks:

  - name: remove libvirt nameserver
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver 192.168.122.1'
      state: absent

 #- name: firewalld is disabled
 #  systemd: name=firewalld enabled=no state=stopped

  - name: disable selinux
    ansible.posix.selinux:
      state: disabled

  - name: packages
    yum:
      name:
      - container-selinux
      - selinux-policy-base
      - bash-completion
      - tree
      - vim
      - git
      state: present

  - name: docker repo
    copy:
      src: ./files/docker-ce.repo
      dest: /etc/yum.repos.d/
      mode: preserve

  - name: install docker components
    yum:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present

  - name: docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: get swarm state
    command: "{% raw %}docker info --format '{{.Swarm.LocalNodeState}}'{% endraw %}"
    register: swarm_state
 
- hosts: managers
  become: yes

  tasks:

  - name: swarm init
    command: "docker swarm init --advertise-addr {{ ansible_host }}"
    when: swarm_state.stdout == "inactive"

  - name: get worker token
    shell: "docker swarm join-token worker | grep 'docker swarm'"
    register: worker_join

  - name: set token facts
    set_fact:
      worker_join_command: "{{ worker_join.stdout }}"

- hosts: workers
  become: yes

  tasks:

  - name: swarm join
    command: "{{ hostvars['node1']['worker_join_command'] }}"
    when: swarm_state.stdout == "inactive"
