# name: firewalld is disabled
# systemd: name=firewalld enabled=no state=stopped

- name: disable selinux
  ansible.posix.selinux:
    state: disabled

- name: packages
  yum:
    name:
    - container-selinux
    - selinux-policy-base
    - kernel-modules-extra
    state: present
  register: task_result

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: task_result is changed

- name: add xt_addrtype module
  community.general.modprobe:
    name: xt_addrtype
    state: present
    persistent: present

- name: docker repo
  copy:
    src: ./files/docker-ce.repo
    dest: /etc/yum.repos.d/
    mode: preserve

- name: install docker components
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: docker service
  service:
    name: docker
    state: started
    enabled: true

- name: get swarm state
  command: "{% raw %}docker info --format '{{.Swarm.LocalNodeState}}'{% endraw %}"
  register: swarm_state
